apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.envname }}-homelabmaindb-exporter"
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: staging
  source:
    path: "exporter"
    repoURL: https://github.com/chestercodes/homelab-maindb.git
    targetRevision: "{{ .Values.apps.homelabmaindbexporter.deploy.revision }}"
    helm:
      valueFiles:
        - values.all.yaml
        - values.base.yaml
      values: |
        is_production: false
        deploying_workflow_name: {{ .Values.deploying_workflow_name }}
        deploy_revision: {{ .Values.apps.homelabmaindbexporter.deploy.revision }}
        app_name: homelabmaindbexporter
  destination:
    namespace: "{{ .Values.envname }}"
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
