apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-cloudflared-tunnel
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: change_me
    repoURL: https://github.com/chestercodes/homelab-apps.git
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

