apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - tunnel-config.yaml

patchesJson6902:
  - target:
      group: traefik.containo.us
      version: v1alpha1
      kind: IngressRoute
      name: homelabping-ingress
    patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: Host(`homelabping.mypersonaltld.com`)
